module.exports =
  # Vacation request form
  REQUEST_FORM_SET_DATES_ARE_VALID: 'REQUEST_FORM_SET_DATES_ARE_VALID'
  REQUEST_FORM_SET_ERROR: 'REQUEST_FORM_SET_ERROR'
  REQUEST_FORM_SET_SELECTED_DATES: 'REQUEST_FORM_SET_SELECTED_DATES'
  REQUEST_FORM_SET_SHOW_FORM: 'REQUEST_FORM_SET_SHOW_FORM'
  REQUEST_FORM_RESET_FORM: 'REQUEST_FORM_RESET_FORM'

  # Grant Vacation Days Form
  GRANT_FORM_SET_SHOW_FORM: 'GRANT_FORM_SET_SHOW_FORM'
  GRANT_FORM_USERS_LOADED: 'GRANT_FORM_USERS_LOADED'

  # Public calendar
  SET_MONTH_PUBLIC_HOLIDAYS: 'SET_MONTH_PUBLIC_HOLIDAYS'

  # Vacation requests
  VACATION_REQUESTS_RECEIVED: 'VACATION_REQUESTS_RECEIVED'
  ADD_VACATION_REQUESTS: 'ADD_VACATION_REQUESTS'
  VACATION_REQUEST_APPROVED: 'VACATION_REQUEST_APPROVED'
  VACATION_REQUEST_REJECTED: 'VACATION_REQUEST_REJECTED'
  VACATION_REQUEST_REPLACE: 'VACATION_REQUEST_REPLACE'

  # Edit vacation requests
  EDIT_VACATION_REQUEST_SET: 'EDIT_VACATION_REQUEST_SET'
  SET_EDIT_SELECTED_DATES: 'SET_EDIT_SELECTED_DATES'
  EDIT_VACATION_REQUEST_ADD_REQUESTED_DAY: 'EDIT_VACATION_REQUEST_ADD_REQUESTED_DAY'
  EDIT_VACATION_REQUEST_REMOVE_REQUESTED_DAY: 'EDIT_VACATION_REQUEST_REMOVE_REQUESTED_DAY'
  EDIT_VACATION_REQUEST_REPLACE_REQUESTED_DAY: 'EDIT_VACATION_REQUEST_REPLACE_REQUESTED_DAY'

  PUBLIC_HOLIDAYS_SET_MONTH_HOLIDAYS: 'PUBLIC_HOLIDAYS_SET_MONTH_HOLIDAYS'

  SET_MONTH_REQUESTED_DAYS: 'SET_MONTH_REQUESTED_DAYS'
  ADD_NEW_PUBLIC_HOLIDAY: 'ADD_NEW_PUBLIC_HOLIDAY'
  SET_PUBLIC_HOLIDAY_VALUES: 'SET_PUBLIC_HOLIDAY_VALUES'
  REMOVE_PUBLIC_HOLIDAY: 'REMOVE_PUBLIC_HOLIDAY'
  INVALIDATE_PUBLIC_HOLIDAYS: 'INVALIDATE_PUBLIC_HOLIDAYS'
  PUBLIC_HOLIDAYS_CREATION_SUCCESS: 'PUBLIC_HOLIDAYS_CREATION_SUCCESS'
  RETRIEVED_YEAR_PUBLIC_HOLIDAYS: 'RETRIEVED_YEAR_PUBLIC_HOLIDAYS'
  DUPLICATE_YEAR_PUBLIC_HOLIDAYS: 'DUPLICATE_YEAR_PUBLIC_HOLIDAYS'
  SET_PUBLIC_HOLIDAY_EDIT_MODE: 'SET_PUBLIC_HOLIDAY_EDIT_MODE'
  PUBLIC_HOLIDAYS_UPDATE_SUCCESS: 'PUBLIC_HOLIDAYS_UPDATE_SUCCESS'
  PUBLIC_HOLIDAY_DESTROYED: 'PUBLIC_HOLIDAY_DESTROYED'

  # Users
  USERS_RECEIVED: 'USERS_RECEIVED'
  REPLACE_USER: 'REPLACE_USER'
  ADD_USER: 'ADD_USER'
  USER_PROFILE_LOADED: 'USER_PROFILE_LOADED'

  # User form
  SET_SHOW_USER_FORM: 'SET_SHOW_USER_FORM'
  SET_USER_FORM_ITEM: 'SET_USER_FORM_ITEM'
  ADD_USER_FORM_ERRORS: 'ADD_USER_FORM_ERRORS'
  RESET_USER_FORM: 'RESET_USER_FORM'
