module.exports = Marty.createConstants
  requestForm: [
    'SET_DATES_VALIDATED'
    'VACATION_REQUEST_CREATED'
    'SET_ERROR'
    'SET_SELECTED_DATES'
    'SET_SHOW_REQUEST_FORM'
  ]

  vacationRequests: [
    'ADD_VACATION_REQUESTS'
    'VACATION_REQUEST_APPROVED'
    'VACATION_REQUEST_REJECTED'
    'SET_VACATION_REQUEST'
  ]

  editVacationRequest: [
    'SET_EDIT_SELECTED_DATES'
    'ADD_REQUESTED_DAY'
    'REMOVE_REQUESTED_DAY'
    'REPLACE_REQUESTED_DAY'
  ]

  publicHolidays: [
    'SET_MONTH_PUBLIC_HOLIDAYS'
    'SET_MONTH_REQUESTED_DAYS'
    'ADD_NEW_PUBLIC_HOLIDAY'
    'SET_PUBLIC_HOLIDAY_VALUES'
    'REMOVE_PUBLIC_HOLIDAY'
    'INVALIDATE_PUBLIC_HOLIDAYS'
    'PUBLIC_HOLIDAYS_CREATION_SUCCESS'
    'RETRIEVED_YEAR_PUBLIC_HOLIDAYS'
    'DUPLICATE_YEAR_PUBLIC_HOLIDAYS'
    'SET_PUBLIC_HOLIDAY_EDIT_MODE'
    'PUBLIC_HOLIDAYS_UPDATE_SUCCESS'
    'PUBLIC_HOLIDAY_DESTROYED'
  ]

  users: [
    'SET_USERS'
    'SET_SHOW_USER_FORM'
    'SET_USER_FORM_ITEM'
    'ADD_USER_FORM_ERRORS'
    'ADD_USER'
    'REPLACE_USER'
  ]
